# Generated by Django 5.2.17 on 2026-08-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=10)),
                ('modelo_ganador', models.CharField(max_length=50)),
                ('demanda_semanal', models.JSONField(default=list)),
                ('demanda_total', models.FloatField(default=0)),
                ('horizon_weeks', models.PositiveIntegerField(default=4)),
                ('mape', models.FloatField(blank=True, null=True)),
                ('selected_model', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(default='OK', max_length=20)),
            ],
            options={
                'verbose_name': 'Pronóstico',
                'verbose_name_plural': 'Pronósticos',
                'ordering': ['product_code'],
                'indexes': [models.Index(fields=['categoria'], name='dashboard_f_categor_70ebba_idx'), models.Index(fields=['modelo_ganador'], name='dashboard_f_modelo__1143af_idx'), models.Index(fields=['status'], name='dashboard_f_status_c51fcd_idx')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_item', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=255)),
                ('almacen', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=10)),
                ('modelo_ganador', models.CharField(blank=True, default='', max_length=50)),
                ('disponible', models.FloatField(default=0)),
                ('forecasted_demand', models.FloatField(default=0)),
                ('punto_reorden', models.FloatField(default=0)),
                ('cantidad_a_ordenar', models.FloatField(default=0)),
                ('costo', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('valor_orden', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('moq', models.FloatField(default=0)),
                ('lead_time', models.FloatField(default=0)),
                ('mape', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Órdenes de compra',
                'ordering': ['codigo_item', 'almacen'],
                'indexes': [models.Index(fields=['codigo_item'], name='dashboard_p_codigo__d402b0_idx'), models.Index(fields=['almacen'], name='dashboard_p_almacen_712a9f_idx'), models.Index(fields=['categoria'], name='dashboard_p_categor_d45a76_idx'), models.Index(fields=['modelo_ganador'], name='dashboard_p_modelo__6e997b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('origen', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
                ('cantidad', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Transferencia',
                'verbose_name_plural': 'Transferencias',
                'ordering': ['product_code', 'origen', 'destino'],
                'indexes': [models.Index(fields=['product_code'], name='dashboard_t_product_6f2edc_idx'), models.Index(fields=['origen'], name='dashboard_t_origen_1cda79_idx'), models.Index(fields=['destino'], name='dashboard_t_destino_42ae5f_idx')],
            },
        ),
    ]
